### PR TITLE
Create biotool_interactions.py

### PR DESCRIPTION
**Pull request by krdav**
Dirty Python script that takes the bio.tools registry in JSON format, finds interactions between tools by input/output format and write the interactions in a Cytoscape readable format.

### CODE REVIEW

**Comment by magnuspalmblad** [comment]
Very nice, except I could not manage to run it. I tried the "standard" Python 3.5.1, 64-bit, for Windows and get the following error:

Traceback (most recent call last):
  File "C:\Users\nmpalmblad\Desktop\biotools_interactions.py", line 6, in <module>
    data = json.load(data_file)
  File "C:\Users\nmpalmblad\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "C:\Users\nmpalmblad\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 516779: character maps to <undefined>

Any ideas or suggestions? I also have Cygwin.

**Comment by krdav** [comment]
I suppose that it is complaining about the character encoding - it does 
not understand it.
Having the bio.tools repo as JSON file in utf-8 you could specify the 
encoding by switching this:
with open("bio.tools.json") as data_file:
With this:
with open("bio.tools.json", encoding="utf8") as data_file:

/K

**Comment by magnuspalmblad** [comment]
Hi Kristian,

Thanks, that worked! I also managed to get it to run in python3 (Python 3.4.3) under Cygwin without specifying the UTF-8 (the default Cygwin Python is 2.7.10).

I know a few programming languages. Unfortunately, Python is not among them. ☺

Cheers,

Magnus

**Comment by joncison** [comment]
Pls. document this on GitHub, as a usage note somewhere

**Comment by krdav** [comment]
I just added that line, however it seems like I do not have write access to the folder, or maybe I just don't know how to use it... New to github.

**Comment by joncison** [comment]
@krdav ... I've just invited you to join the core-dev team.  Then permission should be all-good

**Pull request merged**
